import fs from 'node:fs/promises';
import path from 'node:path';
import { randomUUID } from 'node:crypto';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import YAML from 'yaml';
import { validateDraft, validateSnapshot } from './core.mjs';
import { atomicWrite, hash, processAlive, readOptional, writeJson } from './durable.mjs';

const run = promisify(execFile);
const activeLocks=new Set();
export const marker='# Managed by Weasel Toolbox. Do not edit this file manually.';
export const manifestName='.weasel-toolbox-managed.json';
const schemaPattern=/^[a-zA-Z0-9_-]{1,80}$/;
const idPattern=/^[A-Za-z0-9-]{20,100}$/;
const journalPath=root=>path.join(path.dirname(root),'operation.json');
const lockPath=userDir=>path.join(userDir,'.weasel-toolbox.lock');
const samePath=(a,b)=>path.resolve(a).toLowerCase()===path.resolve(b).toLowerCase();
const fileHash=async file=>{const b=await readOptional(file);return b===null?null:hash(b);};
const targetName=name=>name===manifestName||/^(?:[a-zA-Z0-9_-]+\.custom\.yaml|weasel_toolbox_[a-zA-Z0-9_-]+\.txt)$/.test(name);

async function safeFile(file) {
  try {const stat=await fs.lstat(file);if(!stat.isFile()||stat.isSymbolicLink())throw Error('TARGET_CONFLICT');}
  catch(e){if(e.code!=='ENOENT')throw e;}
}

export async function readManagedManifest(userDir) {
  const content=await readOptional(path.join(userDir,manifestName));
  if(content===null)return {version:1,files:{}};
  try {
    const value=JSON.parse(content);
    if(value.version!==1||!value.files||Array.isArray(value.files)||typeof value.files!=='object')throw Error();
    for(const [name,sha] of Object.entries(value.files))if(!targetName(name)||name===manifestName||!/^([a-f0-9]{64})$/.test(sha))throw Error();
    return value;
  } catch {throw Error('MANIFEST_INVALID');}
}

function phraseTable(schemaId,drafts) {
  const seen=new Set();
  const rows=drafts.filter(d=>d.schemaIds.includes(schemaId))
    .sort((a,b)=>a.code.localeCompare(b.code)||a.order-b.order||a.text.localeCompare(b.text))
    .filter(d=>{const key=JSON.stringify([d.text,d.code]);if(seen.has(key))return false;seen.add(key);return true;})
    .map(d=>d.text+'\t'+d.code+'\t'+(10000-d.order));
  return '# Rime table\n# coding: utf-8\n#@/db_name\tweasel_toolbox_'+schemaId+'.txt\n#@/db_type\ttabledb\n#\n# no comment\n'+rows.join('\n')+(rows.length?'\n':'');
}
function customYaml(id) {
  return marker+'\npatch:\n  "engine/translators/+":\n    - table_translator@weasel_toolbox_phrase\n  weasel_toolbox_phrase:\n    dictionary: ""\n    user_dict: weasel_toolbox_'+id+'\n    db_class: stabledb\n    enable_completion: false\n    enable_sentence: false\n    initial_quality: 100\n';
}
export function createWritePlan(detection,drafts,manifest={files:{}}) {
  if(detection?.state!=='detected'||!path.isAbsolute(detection.userDir||''))throw Error('RIME_NOT_READY');
  if(!Array.isArray(drafts))throw Error('NO_DRAFTS');
  const known=new Set((detection.schemas||[]).map(s=>s.id));
  for(const d of drafts) {validateDraft(d);if(d.schemaIds.some(id=>!known.has(id)))throw Error('UNKNOWN_SCHEMA');}
  const wanted=new Set(drafts.flatMap(d=>d.schemaIds));
  const previous=Object.keys(manifest.files).flatMap(name=>{
    const m=name.match(/^([a-zA-Z0-9_-]+)\.custom\.yaml$/)||name.match(/^weasel_toolbox_([a-zA-Z0-9_-]+)\.txt$/);return m?[m[1]]:[];
  });
  return [...new Set([...wanted,...previous])].map(schemaId=>{
    if(!schemaPattern.test(schemaId))throw Error('INVALID_SCHEMA');
    return {schemaId,configPath:path.join(detection.userDir,schemaId+'.custom.yaml'),tablePath:path.join(detection.userDir,'weasel_toolbox_'+schemaId+'.txt'),config:wanted.has(schemaId)?customYaml(schemaId):null,table:wanted.has(schemaId)?phraseTable(schemaId,drafts):null};
  });
}
async function ensureSafeTargets(plan,manifest) {
  for(const item of plan)for(const target of [item.configPath,item.tablePath]){
    await safeFile(target);
    const content=await readOptional(target);if(content===null)continue;
    const name=path.basename(target);
    if(!manifest.files[name])throw Error(target.endsWith('.custom.yaml')?'CONFIG_CONFLICT':'TARGET_CONFLICT');
    if(target.endsWith('.custom.yaml')&&!content.toString('utf8').startsWith(marker))throw Error('CONFIG_CONFLICT');
    if(manifest.files[name]!==hash(content))throw Error('EXTERNAL_CHANGE');
  }
}

async function readJournal(root) {
  const bytes=await readOptional(journalPath(root));if(bytes===null)return null;
  try {
    const j=JSON.parse(bytes);
    if(j.version!==1||!idPattern.test(j.backupId)||!path.isAbsolute(j.userDir)||!Array.isArray(j.after)||!['deploy','restore'].includes(j.type))throw Error();
    if(j.after.some(x=>!targetName(x.name)||(x.hash!==null&&!/^[a-f0-9]{64}$/.test(x.hash))))throw Error();
    return j;
  }catch{throw Error('RECOVERY_INVALID');}
}
export async function inspectRecovery(backupRoot,userDir) {
  if(userDir&&activeLocks.has(path.resolve(userDir)))return {state:'busy',blocked:true};
  let journal;
  try{journal=await readJournal(backupRoot);}catch{return {state:'invalid',blocked:true};}
  const dir=journal?.userDir||userDir;
  if(!dir||!path.isAbsolute(dir))return {state:'clear',blocked:false};
  const bytes=await readOptional(lockPath(dir));
  let lock;
  try{lock=bytes?JSON.parse(bytes):null;}catch{return {state:'legacy',blocked:true};}
  if(lock&&lock.pid!==process.pid&&processAlive(lock.pid))return {state:'busy',blocked:true};
  if(journal)return {state:'pending',blocked:true,backupId:journal.backupId,phase:journal.phase,type:journal.type,userDir:journal.userDir};
  if(lock&&lock.version!==2)return {state:'legacy',blocked:true};
  // A stale version-2 lock without a journal precedes target writes, or follows completion.
  if(lock)await fs.unlink(lockPath(dir));
  return {state:'clear',blocked:false};
}
async function acquire(root,userDir) {
  const state=await inspectRecovery(root,userDir);if(state.blocked)throw Error(state.state==='busy'?'WRITE_BUSY':'RECOVERY_REQUIRED');
  const h=await fs.open(lockPath(userDir),'wx').catch(e=>{if(e.code==='EEXIST')throw Error('WRITE_BUSY');throw e;});
  activeLocks.add(path.resolve(userDir));
  try{await h.writeFile(JSON.stringify({version:2,pid:process.pid,startedAt:new Date().toISOString()}));await h.sync();}
  catch(e){activeLocks.delete(path.resolve(userDir));throw e;}finally{await h.close();}
}

export async function readBackup(root,id) {
  if(!idPattern.test(id))throw Error('BACKUP_INVALID');
  const dir=path.join(root,id);
  try {
    const stat=await fs.lstat(dir);if(!stat.isDirectory()||stat.isSymbolicLink())throw Error();
    const value=JSON.parse(await fs.readFile(path.join(dir,'manifest.json'),'utf8'));
    if(value.id!==id||!Array.isArray(value.files))throw Error();
    return {...value,dir};
  }catch{throw Error('BACKUP_INVALID');}
}
async function validatedBackup(root,id,userDir) {
  const backup=await readBackup(root,id);const names=new Set();const contents=[];
  for(const f of backup.files){
    const name=path.basename(f.target||'');
    if(!targetName(name)||names.has(name)||typeof f.existed!=='boolean')throw Error('BACKUP_INVALID');
    names.add(name);
    let content=null;
    if(f.existed){
      if(typeof f.copy!=='string'||path.basename(f.copy)!==f.copy||!f.sha256)throw Error('BACKUP_UNVERIFIED');
      await safeFile(path.join(backup.dir,f.copy));
      content=await readOptional(path.join(backup.dir,f.copy));
      if(content===null||hash(content)!==f.sha256)throw Error('BACKUP_DAMAGED');
    }
    contents.push({name,target:path.join(userDir,name),content});
  }
  if(!names.has(manifestName))throw Error('BACKUP_INVALID');
  let snapshot=null;
  if(backup.recordsHash){
    const b=await readOptional(path.join(backup.dir,'records.json'));
    if(b===null||hash(b)!==backup.recordsHash)throw Error('BACKUP_DAMAGED');
    try{snapshot=validateSnapshot(JSON.parse(b));}catch{throw Error('BACKUP_DAMAGED');}
  }
  return {...backup,contents,snapshot};
}
async function backupTargets(targets,root,userDir,type,store) {
  const id=new Date().toISOString().replace(/[:.]/g,'-')+'-'+randomUUID();
  const dir=path.join(root,id);await fs.mkdir(dir,{recursive:true});
  const files=[];
  for(const [i,target] of [...new Set(targets)].entries()){
    await safeFile(target);const content=await readOptional(target);const copy=content===null?null:i+'-'+path.basename(target);
    if(copy)await atomicWrite(path.join(dir,copy),content);
    files.push({target,existed:content!==null,copy,sha256:content===null?null:hash(content)});
  }
  let recordsHash=null;
  if(store){const content=JSON.stringify(store.snapshot());recordsHash=hash(content);await atomicWrite(path.join(dir,'records.json'),content);}
  const value={id,createdAt:new Date().toISOString(),type,pinned:false,successful:false,userDir,files,recordsHash};
  await writeJson(path.join(dir,'manifest.json'),value);
  await validatedBackup(root,id,userDir);
  return value;
}
async function updateMetadata(root,id,changes){const b=await readBackup(root,id);delete b.dir;await writeJson(path.join(root,id,'manifest.json'),{...b,...changes});}

export async function listBackups(root) {
  let entries;try{entries=await fs.readdir(root,{withFileTypes:true});}catch(e){if(e.code==='ENOENT')return [];throw e;}
  let journal;try{journal=await readJournal(root);}catch{journal={backupId:'*'};}
  const result=[];
  for(const entry of entries){if(!entry.isDirectory())continue;try{
    const b=await readBackup(root,entry.name);let sizeBytes=0;
    for(const f of await fs.readdir(b.dir)){const s=await fs.stat(path.join(b.dir,f));if(s.isFile())sizeBytes+=s.size;}
    result.push({id:b.id,createdAt:b.createdAt,fileCount:b.files.length,sizeBytes,restorable:b.files.every(f=>!f.existed||Boolean(f.copy&&f.sha256)),type:b.type==='safety'?'safety':'deploy',pinned:!!b.pinned,successful:!!b.successful,hasRecords:!!b.recordsHash,protected:journal?.backupId===b.id||journal?.sourceBackupId===b.id||journal?.backupId==='*'});
  }catch{}}
  return result.sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)));
}
export async function setBackupPinned(root,id,pinned){await updateMetadata(root,id,{pinned:!!pinned});return {ok:true};}
export async function deleteBackup(root,id){
  const j=await readJournal(root);if(j&&(j.backupId===id||j.sourceBackupId===id))throw Error('BACKUP_PROTECTED');
  const b=await readBackup(root,id);const target=path.resolve(b.dir);
  if(!target.startsWith(path.resolve(root)+path.sep))throw Error('BACKUP_INVALID');
  await fs.rm(target,{recursive:true});return {ok:true,id};
}
export async function pruneBackups(root,{keepDeploy=20,keepSafety=5}={}){
  const list=await listBackups(root);const keep=new Set(list.filter(b=>b.pinned||b.protected).map(b=>b.id));
  for(const type of ['deploy','safety'])for(const b of list.filter(b=>b.type===type).slice(0,type==='deploy'?keepDeploy:keepSafety))keep.add(b.id);
  const latest=list.find(b=>b.successful);if(latest)keep.add(latest.id);
  const removed=[];for(const b of list)if(!keep.has(b.id)){await deleteBackup(root,b.id);removed.push(b.id);}
  return {removed,count:removed.length};
}
async function defaultRunDeployer(exe){return run(exe,['/deploy'],{windowsHide:true,timeout:120000,maxBuffer:2*1024*1024});}
async function deployer(detection){const exe=path.join(detection.installDir||'','WeaselDeployer.exe');if(!path.isAbsolute(exe))throw Error('DEPLOYER_NOT_FOUND');try{await fs.access(exe);}catch{throw Error('DEPLOYER_NOT_FOUND');}return exe;}
async function verifyContents(contents,detection){
  for(const x of contents){
    if(await fileHash(x.target)!==(x.content===null?null:hash(x.content)))throw Error('DEPLOY_VERIFY_FAILED');
    const match=x.name.match(/^([a-zA-Z0-9_-]+)\.custom\.yaml$/);if(!match||!detection.schemas.some(s=>s.id===match[1]))continue;
    const bytes=await readOptional(path.join(detection.userDir,'build',match[1]+'.schema.yaml'));if(!bytes)throw Error('DEPLOY_VERIFY_FAILED');
    const parsed=YAML.parse(bytes.toString('utf8'),{maxAliasCount:50});
    const present=parsed?.engine?.translators?.includes('table_translator@weasel_toolbox_phrase')===true;
    if(x.content!==null&&(!present||parsed.weasel_toolbox_phrase?.user_dict!=='weasel_toolbox_'+match[1]))throw Error('DEPLOY_VERIFY_FAILED');
    if(x.content===null&&present)throw Error('DEPLOY_VERIFY_FAILED');
  }
}
async function applyContents(contents,hook=async()=>{}){
  for(const x of contents){await safeFile(x.target);if(x.content===null)await fs.unlink(x.target).catch(e=>{if(e.code!=='ENOENT')throw e;});else await atomicWrite(x.target,x.content);await hook('file-written');}
}
async function rollback(root,j,detection,runDeployer,store,verify){
  if(!samePath(j.userDir,detection.userDir))throw Error('TARGET_CHANGED');
  const b=await validatedBackup(root,j.backupId,j.userDir);
  if(b.contents.length!==j.after.length||b.contents.some(x=>!j.after.some(a=>a.name===x.name)))throw Error('RECOVERY_INVALID');
  // Validate all targets before writing. Before/after hashes allow repeated interrupted recovery.
  for(const x of b.contents){await safeFile(x.target);const current=await fileHash(x.target);const before=x.content===null?null:hash(x.content);const after=j.after.find(a=>a.name===x.name)?.hash;if(current!==before&&current!==after)throw Error('EXTERNAL_CHANGE');}
  await writeJson(journalPath(root),{...j,phase:'recovering'});
  await applyContents(b.contents);
  await runDeployer(await deployer(detection));
  await verify(b.contents,detection);
  if(store&&b.snapshot)store.replaceSnapshot(b.snapshot,true);
  else store?.markAllPending();
  await fs.unlink(journalPath(root));
  await fs.unlink(lockPath(j.userDir)).catch(e=>{if(e.code!=='ENOENT')throw e;});
}

async function execute({detection,backupRoot,contents,type,sourceBackupId,store,commit,preflight=async()=>{},runDeployer=defaultRunDeployer,verify=verifyContents,checkpoint=async()=>{}}){
  const exe=await deployer(detection);await fs.mkdir(backupRoot,{recursive:true});await acquire(backupRoot,detection.userDir);
  let journal;
  try{
    await preflight();
    const backup=await backupTargets(contents.map(x=>x.target),backupRoot,detection.userDir,type==='restore'?'safety':'deploy',store);
    journal={version:1,pid:process.pid,type,backupId:backup.id,sourceBackupId,userDir:detection.userDir,phase:'prepared',after:contents.map(x=>({name:x.name,hash:x.content===null?null:hash(x.content)}))};
    await writeJson(journalPath(backupRoot),journal);await checkpoint('prepared');
    await applyContents(contents,checkpoint);
    journal.phase='files-written';await writeJson(journalPath(backupRoot),journal);await checkpoint('files-written');
    await runDeployer(exe);await verify(contents,detection);
    journal.phase='committing';await writeJson(journalPath(backupRoot),journal);await checkpoint('committing');
    await commit?.();await checkpoint('database-committed');
    await updateMetadata(backupRoot,backup.id,{successful:true});
    await fs.unlink(journalPath(backupRoot));journal=null;
    await fs.unlink(lockPath(detection.userDir));
    const cleanup=await pruneBackups(backupRoot).catch(()=>({count:0,removed:[]}));
    return {backupId:backup.id,cleanup};
  }catch(e){
    // Test-only loss-of-process simulation; normal failures always attempt rollback.
    if(e.simulatedPowerLoss)throw e;
    if(journal){try{await rollback(backupRoot,journal,detection,runDeployer,store,verify);}catch{throw Error('RECOVERY_REQUIRED');}}
    else await fs.unlink(lockPath(detection.userDir)).catch(()=>{});
    throw e;
  }finally{
    activeLocks.delete(path.resolve(detection.userDir));
  }
}
export async function deployDrafts(options){
  const {detection,drafts,backupRoot,store}=options;
  const manifest=await readManagedManifest(detection.userDir);
  const manifestHash=await fileHash(path.join(detection.userDir,manifestName));
  const plan=createWritePlan(detection,drafts,manifest);await ensureSafeTargets(plan,manifest);
  if(!plan.length)throw Error('NO_DRAFTS');
  const files={};const contents=[];
  for(const p of plan)for(const [target,content] of [[p.configPath,p.config],[p.tablePath,p.table]]){
    const name=path.basename(target);contents.push({name,target,content});if(content!==null)files[name]=hash(content);
  }
  // Store classification in the management manifest; leave Rime table syntax unchanged.
  const meta=JSON.stringify({version:1,files,records:drafts.map(d=>validateDraft(d)),updatedAt:new Date().toISOString()},null,2);
  contents.push({name:manifestName,target:path.join(detection.userDir,manifestName),content:meta});
  const preflight=async()=>{if(await fileHash(path.join(detection.userDir,manifestName))!==manifestHash)throw Error('EXTERNAL_CHANGE');await ensureSafeTargets(plan,manifest);};
  const result=await execute({...options,contents,type:'deploy',preflight,commit:()=>store?.markDeployed(),verify:options.verify?()=>options.verify(plan,detection.userDir):verifyContents});
  return {ok:true,...result,schemas:plan.map(p=>p.schemaId),draftCount:drafts.length,status:'deployed_pending_input_test'};
}
export async function restoreManagedBackup(options){
  const {detection,backupRoot,backupId,store}=options;
  if(detection.state!=='detected')throw Error('RIME_NOT_READY');
  const source=await validatedBackup(backupRoot,backupId,detection.userDir);
  if(source.userDir&&!samePath(source.userDir,detection.userDir))throw Error('TARGET_CHANGED');
  const current=await readManagedManifest(detection.userDir);
  const byName=new Map(source.contents.map(x=>[x.name,x]));
  for(const name of Object.keys(current.files))if(!byName.has(name))byName.set(name,{name,target:path.join(detection.userDir,name),content:null});
  const contents=[...byName.values()];
  const manifestHash=await fileHash(path.join(detection.userDir,manifestName));
  const preflight=async()=>{
  if(await fileHash(path.join(detection.userDir,manifestName))!==manifestHash)throw Error('EXTERNAL_CHANGE');
  for(const x of contents){
    await safeFile(x.target);if(x.name===manifestName)continue;
    const existing=await readOptional(x.target);if(existing!==null&&current.files[x.name]!==hash(existing))throw Error('EXTERNAL_CHANGE');
  }
  };
  await preflight();
  const result=await execute({...options,contents,preflight,type:'restore',sourceBackupId:backupId,commit:()=>source.snapshot?store?.replaceSnapshot(source.snapshot,true):store?.markAllPending()});
  return {ok:true,backupId,safetyBackupId:result.backupId,hasRecords:!!source.snapshot,cleanup:result.cleanup,status:'restored_pending_input_test'};
}
export async function recoverInterrupted({detection,backupRoot,store,runDeployer=defaultRunDeployer,verify=verifyContents}){
  const state=await inspectRecovery(backupRoot,detection.userDir);if(state.state!=='pending')throw Error(state.state==='busy'?'WRITE_BUSY':'RECOVERY_INVALID');
  if(detection.state!=='detected')throw Error('RIME_NOT_READY');
  const j=await readJournal(backupRoot);
  if(!samePath(j.userDir,detection.userDir))throw Error('TARGET_CHANGED');
  activeLocks.add(path.resolve(j.userDir));
  try{
    await writeJson(lockPath(j.userDir),{version:2,pid:process.pid,startedAt:new Date().toISOString()});
    await rollback(backupRoot,j,detection,runDeployer,store,verify);
  }finally{activeLocks.delete(path.resolve(j.userDir));}
  return {ok:true};
}
