import fs from 'node:fs/promises';
import { constants } from 'node:fs';
import path from 'node:path';
import { createHash, randomUUID } from 'node:crypto';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';

const execFileAsync=promisify(execFile);
const marker='# Managed by Weasel Toolbox. Do not edit this file manually.';
const manifestName='.weasel-toolbox-managed.json';

const sha256=value=>createHash('sha256').update(value).digest('hex');
const exists=value=>fs.access(value).then(()=>true,()=>false);

function phraseTable(schemaId,drafts) {
  const name=`weasel_toolbox_${schemaId}`;
  const rows=drafts
    .filter(d=>d.schemaIds.includes(schemaId))
    .sort((a,b)=>a.code.localeCompare(b.code)||a.order-b.order||a.text.localeCompare(b.text))
    .map(d=>`${d.text}\t${d.code}\t${10000-d.order}`);
  return `# Rime table\n# coding: utf-8\n#@/db_name\t${name}.txt\n#@/db_type\ttabledb\n#\n# no comment\n${rows.join('\n')}${rows.length?'\n':''}`;
}

function customYaml(schemaId) {
  return `${marker}\npatch:\n  "engine/translators/+":\n    - table_translator@weasel_toolbox_phrase\n  weasel_toolbox_phrase:\n    dictionary: ""\n    user_dict: weasel_toolbox_${schemaId}\n    db_class: stabledb\n    enable_completion: false\n    enable_sentence: false\n    initial_quality: 100\n`;
}

export function createWritePlan(detection,drafts) {
  if(detection?.state!=='detected'||!path.isAbsolute(detection.userDir||'')) throw new Error('RIME_NOT_READY');
  if(!Array.isArray(drafts)) throw new Error('NO_DRAFTS');
  const known=new Set((detection.schemas||[]).map(s=>s.id));
  if(drafts.some(d=>d.schemaIds.some(id=>!known.has(id)))) throw new Error('UNKNOWN_SCHEMA');
  return [...known].map(schemaId=>({
    schemaId,
    configPath:path.join(detection.userDir,`${schemaId}.custom.yaml`),
    tablePath:path.join(detection.userDir,`weasel_toolbox_${schemaId}.txt`),
    config:customYaml(schemaId),
    table:phraseTable(schemaId,drafts)
  }));
}

async function atomicWrite(target,content) {
  const temp=`${target}.${randomUUID()}.tmp`;
  await fs.writeFile(temp,content,{encoding:'utf8',flag:'wx'});
  try { await fs.rename(temp,target); }
  catch(error){ await fs.unlink(temp).catch(()=>{}); throw error; }
}

async function readManagedManifest(userDir) {
  const file=path.join(userDir,manifestName);
  if(!await exists(file)) return {version:1,files:{}};
  try { const value=JSON.parse(await fs.readFile(file,'utf8')); return value?.version===1&&value.files?value:{version:1,files:{}}; }
  catch { throw new Error('MANIFEST_INVALID'); }
}

async function ensureSafeTargets(plan,manifest) {
  for(const item of plan) {
    for(const target of [item.configPath,item.tablePath]) {
      if(!await exists(target)) continue;
      const content=await fs.readFile(target,'utf8');
      const name=path.basename(target);
      if(!manifest.files[name]) throw new Error(target.endsWith('.custom.yaml')?'CONFIG_CONFLICT':'TARGET_CONFLICT');
      if(target.endsWith('.custom.yaml')&&!content.startsWith(marker)) throw new Error('CONFIG_CONFLICT');
      if(manifest.files[name]&&manifest.files[name]!==sha256(content)) throw new Error('EXTERNAL_CHANGE');
    }
  }
}

async function backupTargets(plan,backupRoot,userDir,{type='deploy'}={}) {
  const id=`${new Date().toISOString().replace(/[:.]/g,'-')}-${randomUUID()}`;
  const dir=path.join(backupRoot,id);
  await fs.mkdir(dir,{recursive:true});
  const files=[];
  const targets=[path.join(userDir,manifestName),...plan.flatMap(p=>[p.configPath,p.tablePath])];
  for(const [index,target] of [...new Set(targets)].entries()) {
    const present=await exists(target);
    const copy=present?`${index}-${path.basename(target)}`:null;
    if(present) await fs.copyFile(target,path.join(dir,copy),constants.COPYFILE_EXCL);
    files.push({target,existed:present,copy,sha256:present?sha256(await fs.readFile(target)):null});
  }
  await fs.writeFile(path.join(dir,'manifest.json'),JSON.stringify({id,createdAt:new Date().toISOString(),type,pinned:false,successful:false,files},null,2),'utf8');
  return {id,dir,files};
}

async function restoreBackup(backup) {
  for(const item of backup.files) {
    if(item.existed) await atomicWrite(item.target,await fs.readFile(path.join(backup.dir,item.copy),'utf8'));
    else await fs.unlink(item.target).catch(error=>{if(error.code!=='ENOENT')throw error;});
  }
}

async function readBackup(backupRoot,id) {
  if(!/^[A-Za-z0-9-]{20,100}$/.test(id)) throw new Error('BACKUP_INVALID');
  const dir=path.join(backupRoot,id);
  let value;
  try { value=JSON.parse(await fs.readFile(path.join(dir,'manifest.json'),'utf8')); }
  catch { throw new Error('BACKUP_INVALID'); }
  if(value.id!==id||!Array.isArray(value.files)) throw new Error('BACKUP_INVALID');
  return {...value,dir};
}

export async function listBackups(backupRoot) {
  let entries=[];try{entries=await fs.readdir(backupRoot,{withFileTypes:true});}catch(error){if(error.code==='ENOENT')return [];throw error;}
  const result=[];
  for(const entry of entries) {
    if(!entry.isDirectory()) continue;
    try {
      const backup=await readBackup(backupRoot,entry.name);
      let sizeBytes=0;
      for(const file of await fs.readdir(backup.dir)){const stat=await fs.stat(path.join(backup.dir,file));if(stat.isFile())sizeBytes+=stat.size;}
      result.push({id:backup.id,createdAt:backup.createdAt,fileCount:backup.files.length,sizeBytes,restorable:backup.files.every(f=>!f.existed||Boolean(f.copy&&f.sha256)),type:backup.type==='safety'?'safety':'deploy',pinned:Boolean(backup.pinned),successful:Boolean(backup.successful)});
    }
    catch {}
  }
  return result.sort((a,b)=>b.createdAt.localeCompare(a.createdAt));
}

async function updateBackupMetadata(backupRoot,id,changes) {
  const backup=await readBackup(backupRoot,id);
  const value={...backup,...changes};delete value.dir;
  await atomicWrite(path.join(backup.dir,'manifest.json'),JSON.stringify(value,null,2));
  return value;
}

export async function setBackupPinned(backupRoot,id,pinned) {
  await updateBackupMetadata(backupRoot,id,{pinned:Boolean(pinned)});
  return {ok:true,id,pinned:Boolean(pinned)};
}

export async function deleteBackup(backupRoot,id) {
  const backup=await readBackup(backupRoot,id);
  const root=path.resolve(backupRoot);const target=path.resolve(backup.dir);
  if(!target.startsWith(root+path.sep)) throw new Error('BACKUP_INVALID');
  await fs.rm(target,{recursive:true,force:false});
  return {ok:true,id};
}

export async function pruneBackups(backupRoot,{keepDeploy=20,keepSafety=5}={}) {
  const backups=await listBackups(backupRoot);const keep=new Set(backups.filter(item=>item.pinned).map(item=>item.id));
  for(const item of backups.filter(item=>item.type==='deploy').slice(0,keepDeploy))keep.add(item.id);
  for(const item of backups.filter(item=>item.type==='safety').slice(0,keepSafety))keep.add(item.id);
  const latestSuccessful=backups.find(item=>item.successful);if(latestSuccessful)keep.add(latestSuccessful.id);
  const removed=[];
  for(const item of backups){if(keep.has(item.id))continue;await deleteBackup(backupRoot,item.id);removed.push(item.id);}
  return {removed,count:removed.length};
}

async function defaultRunDeployer(deployerPath) {
  return execFileAsync(deployerPath,['/deploy'],{windowsHide:true,timeout:120000,maxBuffer:2*1024*1024});
}

async function defaultVerify(plan,userDir) {
  for(const item of plan) {
    const built=path.join(userDir,'build',`${item.schemaId}.schema.yaml`);
    const content=await fs.readFile(built,'utf8');
    if(!content.includes('table_translator@weasel_toolbox_phrase')||!content.includes(`user_dict: weasel_toolbox_${item.schemaId}`)) throw new Error('DEPLOY_VERIFY_FAILED');
  }
}

export async function deployDrafts({detection,drafts,backupRoot,runDeployer=defaultRunDeployer,verify=defaultVerify}) {
  const plan=createWritePlan(detection,drafts);
  const deployerPath=path.join(detection.installDir||'','WeaselDeployer.exe');
  if(!path.isAbsolute(deployerPath)||!await exists(deployerPath)) throw new Error('DEPLOYER_NOT_FOUND');
  await fs.mkdir(backupRoot,{recursive:true});
  const lockPath=path.join(detection.userDir,'.weasel-toolbox.lock');
  let lock;
  try { lock=await fs.open(lockPath,'wx'); await lock.writeFile(JSON.stringify({pid:process.pid,startedAt:new Date().toISOString()})); }
  catch(error){ if(error.code==='EEXIST') throw new Error('WRITE_BUSY'); throw error; }
  let backup;
  try {
    const oldManifest=await readManagedManifest(detection.userDir);
    await ensureSafeTargets(plan,oldManifest);
    backup=await backupTargets(plan,backupRoot,detection.userDir,{type:'deploy'});
    const files={};
    for(const item of plan) {
      await atomicWrite(item.configPath,item.config); files[path.basename(item.configPath)]=sha256(item.config);
      await atomicWrite(item.tablePath,item.table); files[path.basename(item.tablePath)]=sha256(item.table);
    }
    await atomicWrite(path.join(detection.userDir,manifestName),JSON.stringify({version:1,updatedAt:new Date().toISOString(),files},null,2));
    await runDeployer(deployerPath);
    await verify(plan,detection.userDir);
    await updateBackupMetadata(backupRoot,backup.id,{successful:true});
    const cleanup=await pruneBackups(backupRoot).catch(()=>({removed:[],count:0}));
    return {ok:true,backupId:backup.id,schemas:plan.map(p=>p.schemaId),draftCount:drafts.length,cleanup,status:'deployed_pending_input_test'};
  } catch(error) {
    if(backup) {
      await restoreBackup(backup).catch(()=>{});
      await runDeployer(deployerPath).catch(()=>{});
    }
    throw error;
  } finally {
    await lock?.close().catch(()=>{});
    await fs.unlink(lockPath).catch(()=>{});
  }
}

export async function restoreManagedBackup({detection,backupRoot,backupId,runDeployer=defaultRunDeployer}) {
  const plan=createWritePlan(detection,[]);
  const deployerPath=path.join(detection.installDir||'','WeaselDeployer.exe');
  if(!path.isAbsolute(deployerPath)||!await exists(deployerPath)) throw new Error('DEPLOYER_NOT_FOUND');
  const source=await readBackup(backupRoot,backupId);
  const targetByName=new Map([path.join(detection.userDir,manifestName),...plan.flatMap(p=>[p.configPath,p.tablePath])].map(p=>[path.basename(p),p]));
  const seen=new Set();const files=[];
  for(const item of source.files) {
    const name=path.basename(item.target||'');const target=targetByName.get(name);
    if(!target||seen.has(name)) throw new Error('BACKUP_INVALID');seen.add(name);
    if(item.existed) {
      if(!item.copy||path.basename(item.copy)!==item.copy||!item.sha256) throw new Error('BACKUP_UNVERIFIED');
      const content=await fs.readFile(path.join(source.dir,item.copy));
      if(sha256(content)!==item.sha256) throw new Error('BACKUP_DAMAGED');
    }
    files.push({...item,target});
  }
  if(seen.size!==targetByName.size) throw new Error('BACKUP_INVALID');
  const lockPath=path.join(detection.userDir,'.weasel-toolbox.lock');let lock;
  try { lock=await fs.open(lockPath,'wx');await lock.writeFile(JSON.stringify({pid:process.pid,startedAt:new Date().toISOString(),operation:'restore'})); }
  catch(error){if(error.code==='EEXIST')throw new Error('WRITE_BUSY');throw error;}
  let safety;
  try {
    safety=await backupTargets(plan,backupRoot,detection.userDir,{type:'safety'});
    await restoreBackup({...source,files});
    await runDeployer(deployerPath);
    for(const item of plan) {
      const built=await fs.readFile(path.join(detection.userDir,'build',`${item.schemaId}.schema.yaml`),'utf8');
      const configEntry=files.find(f=>f.target===item.configPath);
      const shouldExist=Boolean(configEntry?.existed);
      if(shouldExist!==built.includes('table_translator@weasel_toolbox_phrase')) throw new Error('RESTORE_VERIFY_FAILED');
    }
    await updateBackupMetadata(backupRoot,safety.id,{successful:true});
    const cleanup=await pruneBackups(backupRoot).catch(()=>({removed:[],count:0}));
    return {ok:true,backupId,status:'restored_pending_input_test',safetyBackupId:safety.id,cleanup};
  } catch(error) {
    if(safety){await restoreBackup(safety).catch(()=>{});await runDeployer(deployerPath).catch(()=>{});}
    throw error;
  } finally {await lock?.close().catch(()=>{});await fs.unlink(lockPath).catch(()=>{});}
}
